name: CI/CD actions

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-2025

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install missing SW tools
        run: |
          choco install cppcheck
          winget upgrade --id Kitware.CMake -e --accept-package-agreements --accept-source-agreements
          $url = "https://developer.arm.com/-/media/Files/downloads/gnu/14.2.rel1/binrel/arm-gnu-toolchain-14.2.rel1-mingw-w64-x86_64-arm-none-eabi.zip"
          $pathToFile = "${{runner.temp}}\arm-gnu.zip"
          $extractPath = "${{github.workspace}}\arm-gnu"
          Invoke-WebRequest -Uri $url -OutFile $pathToFile
          Expand-Archive -Path $pathToFile -DestinationPath $extractPath -Force

      - name: Build firmware with Arm-GNU toolchain
        run: |
          $env:Path ="${{github.workspace}}\arm-gnu\bin;" + $env:Path
          cmake -G "Ninja" -S .\ -B .\build
          cmake --build .\build

      - name: Create source file list for static analysis and format checks
        run: python .\cicd_pipeline\script\generate_source_file_list.py .\ source_file_list.txt

      - name: Check code style with clang-format
        run: clang-format --Werror --dry-run --verbose --style=file --files=source_file_list.txt

      # Disable clang-tidy check temporarily since code is not yet compiliant
      #- name: Run static analysis with clang-tidy
      #  run: python ".\cicd_pipeline\script\run-clang-tidy.py" -quiet -config-file ".clang-tidy" -p ".\build" -source-filter "^(?!.*?pico-sdk).*$"

      - name: Run static analysis with Cppcheck
        run: |
          # Runner has another cppcheck.exe installed that is broken. To prevent calling it, add the correct version first in the Path.
          $env:Path = "C:\Program Files\Cppcheck;" + $env:Path
          cppcheck `
            --check-level=exhaustive `
            --enable=all `
            --inconclusive `
            --suppress=missingIncludeSystem `
            --suppress=missingInclude `
            --inline-suppr `
            --file-list=source_file_list.txt `
            --error-exitcode=1
